### PR TITLE
Fixes ActionView::Template::Error vm_type Error

### LINKED ISSUE #150: ActionView::Template::Error undefined method `type' for nil:NilClass
ActionView::Template::Error undefined method `type' for nil:NilClass while creating proxmox host.

I get the error when creating proxmox host using bootdisk as provision method. But this has noting to do with bootdisk provisioning as I debugged and the error occurred before even reaching the foreman_boodisk proxmox extension iso_upload method of PR: https://github.com/theforeman/foreman_bootdisk/pull/90

**Error**:
The error is as follows: 
`ActionView::Template::Error undefined method 'type' for nil:NilClass
/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_fog_proxmox0.10.2/app/helpers/proxmox_vm_helper.rb:90:in 'vm_type' `

In Production log: 
```
ActionView::Template::Error (undefined method 'type' for nil:NilClass):
17:40:03 rails.1   | 2020-05-24T17:40:03 [F|app|15d6a095]     28: along with ForemanFogProxmox. If not, see <http://www.gnu.org/licenses/>. %>

17:40:03 rails.1   |  |     29: <% if @host.compute_resource.class == ForemanFogProxmox::Proxmox %>

17:40:03 rails.1   |  |     30: <% compute_attributes = f.object.compute_attributes %>

17:40:03 rails.1   |  |     31: <% vm_type = vm_type(@host) %>

17:40:03 rails.1   |  |     32: <% node_id = node_id(@host) %>

```
In foreman_fog_proxmox : https://github.com/theforeman/foreman_fog_proxmox/blob/c112ba30e275feb8b0694869c9c2f5fdb4507216/app/views/compute_resources_vms/form/proxmox/_add_vm_type_to_nic_provider_specific_form.html.erb#L19

 **Versions**:
Foreman 1.24
Foreman_fog_proxmox 0.10 and above

**Additional Information**:
This error is not produced when I use foreman_fog_proxmox < 0.10.0 , i.e,  foreman_fog_proxmox 0.9.x
OR
When I replace lines  in https://github.com/theforeman/foreman_fog_proxmox/blob/c112ba30e275feb8b0694869c9c2f5fdb4507216/app/views/compute_resources_vms/form/proxmox/_add_vm_type_to_nic_provider_specific_form.html.erb

From: 

``` 
<% vm_type = vm_type(@host) %>
<% node_id = node_id(@host) %> 
```

To: 
```
<% vm_type = f.object.respond_to?('type') ? f.object.type : nil %>
<% node_id = f.object.respond_to?('node_id') ? f.object.node_id : nil %>
```

### PR DESCRIPTION
**Pull request by Manisha15**
Fixes Issue: https://github.com/theforeman/foreman_fog_proxmox/issues/150

### CODE REVIEW

**Comment by tristanrobert** [comment]
Thank you for your PR. I understand your need but first I need to analyze and test why you need to rollback this feature. I need to test what is exactly your bug before to merge or not.

**Comment by Manisha15** [comment]
To produce the error you can pull my PR https://github.com/theforeman/foreman_bootdisk/pull/90 and try to create proxmox host using bootdisk as provision method on foreman with foreman_fog_proxmox > 0.9.x or @hakong also have same error and mentioned the way to produce it. TIA.

**Comment by tristanrobert** [comment]
ok @Manisha15 I will try your PR and test your bug.

**Comment by sbernhard** [comment]
@tristanrobert , did you have the time to test the PR from @Manisha15? How can we help to get this done as it blocks the change in foreman_bootdisk, too.

**Comment by Manisha15** [comment]
> ok @Manisha15 I will try your PR and test your bug.

Hello @tristanrobert, Did you get the time to check this PR? It would be helpful if you can review this, so that the other blocked PR can also get merged. TIA

**Comment by tristanrobert** [comment]
@Manisha15  could you please complete your PR by deleting the two functions: `vm_type(host)` and `node_id(host)` in [`proxmox_vm_helper.rb`](https://github.com/theforeman/foreman_fog_proxmox/blob/c112ba30e275feb8b0694869c9c2f5fdb4507216/app/helpers/proxmox_vm_helper.rb#L89). They are only used in [`_add_vm_type_to_nic_provider_specific_form.html.erb`](https://github.com/theforeman/foreman_fog_proxmox/blob/c112ba30e275feb8b0694869c9c2f5fdb4507216/app/views/compute_resources_vms/form/proxmox/_add_vm_type_to_nic_provider_specific_form.html.erb#L19)

**Comment by Manisha15** [comment]
> @Manisha15 could you please complete your PR by deleting the two functions: `vm_type(host)` and `node_id(host)` in [`proxmox_vm_helper.rb`](https://github.com/theforeman/foreman_fog_proxmox/blob/c112ba30e275feb8b0694869c9c2f5fdb4507216/app/helpers/proxmox_vm_helper.rb#L89). They are only used in [`_add_vm_type_to_nic_provider_specific_form.html.erb`](https://github.com/theforeman/foreman_fog_proxmox/blob/c112ba30e275feb8b0694869c9c2f5fdb4507216/app/views/compute_resources_vms/form/proxmox/_add_vm_type_to_nic_provider_specific_form.html.erb#L19)

Done !

**Comment by tristanrobert** [comment]
You have introduced a syntax error on proxmox_compute_attributes.rb file at line 57: delete the colon `:` at the end of the line. See CI build logs.

**Comment by sbernhard** [comment]
done :)

**Comment by tristanrobert** [comment]
Thank you @sbernhard and @Manisha15 !

**Pull request merged**
